name: 社会大数据与知识工程研究组
url: http://www.dviz.cn/sbdkg

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html


# Sections on the "people" page.
roles:
  - key: faculty
    name: 研究人员
  - key: staff
    name: 员工
  - key: doctor_student
    name: 博士研究生
  - key: master_student
    name: 硕士研究生
  - key: collab
    name: 合作者
  - key: alum
    name: 毕业生
  - key: special_faculty
    name: 特聘专家

# Number of news stories on the front page.
front_page_news: 8

front_page_pres: 3

# Base pathname for links.
base: ''

# make pages for the _projects folder




collections:
  projects:
    output: true
  papers:
    output: true
    permalink: /paper/:year/:month/:day/:title.html




# Navigation bar links.
navigation:
  - title: 主页
    link: /
  - title: 人员
    link: /people.html
  - title: 项目
    link: /research.html
  - title: 成果
    link: /publications.html
  - title: 代码
    link: /code.html
 # - title: 合作
 #   link: /fund.html
